apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: integration
  name: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: integration
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/sro-net: "true"
        io.kompose.service: integration
    spec:
      containers:
        - image: integration
          name: sro-integration
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
