apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sro
  namespace: argocd
  
spec:
  description: SRO
  sourceRepos:
  - '*'
  destinations:
  - namespace: sro
    server: https://kubernetes.default.svc
  - namespace: "pr-*"
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"