apiVersion: v1
kind: Pod
metadata:
  #annotations:
  #  kompose.cmd: kompose convert -f docker-compose.yaml
  #  kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/sro-net: "true"
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  containers:
    - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: sro-dev
        - name: RABBITMQ_DEFAULT_USER
          value: sro-dev
      image: rabbitmq:3-management
      livenessProbe:
        exec:
          command:
            - rabbitmq-diagnostics -q ping
        failureThreshold: 3
        periodSeconds: 30
        timeoutSeconds: 30
      name: sro-rabbitmq
      ports:
        - containerPort: 5672
        - containerPort: 15672
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-volume
  restartPolicy: OnFailure
  volumes:
    - name: rabbitmq-volume
      persistentVolumeClaim:
        claimName: rabbitmq-volume
status: {}
