apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/sro-net: "true"
    io.kompose.service: optimizer
  name: optimizer
spec:
  containers:
    - image: optimizer
      name: sro-optimizer
      resources: {}
  restartPolicy: OnFailure
status: {}
