apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.network/sro-net: "true"
    io.kompose.service: api
  name: api
spec:
  containers:
    - env:
        - name: PHZR_SRO_AMQPURL
          value: "amqp://rabbitmq.default.svc.cluster.local:15672"
        - name: PHZR_SRO_MONGO_URL
          value: "mongodb://mongo.default.svc.cluster.local:27017"
      image: sro-registry:5000/sro_api:latest
      name: sro-api
      resources: {}
  restartPolicy: OnFailure
status: {}
